global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "lab-app"
    static_configs:
      - targets: ["app:8080"]

remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"
