name: Deploy with Docker Compose

on:
  push:
    branches:
      - master
  workflow_dispatch: # Позволяет запускать вручную из интерфейса GitHub

jobs:
  deploy:
    name: Deploy to VPS with Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to VPS
        run: |
          scp -o StrictHostKeyChecking=no \
            docker-compose.yaml .env ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/lab

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd ~/lab

          docker compose down

          docker compose up -d
          EOF
